name: udp-flooder
services:
  - name: udp-flooder-service
    type: worker  # Since it's not a web app, use "worker"
    dockerfile: ./Dockerfile
    env:
      - name: TARGET_IP
        value: "192.168.1.1"
      - name: TARGET_PORT
        value: "56"
      - name: PACKET_SIZE
        value: "200"
      - name: THREADS
        value: "2000"
    build:
      command: "pip install -r requirements.txt"
    run:
      command: "gcc -o bgmi newvpsbest.c -lpthread -lrt"
    run:
      command: "python vps1.py"  # Start your script
