name: udp-flooder
services:
  - name: udp-flooder-service
    type: worker  # Since it's not a web app, use "worker"
    dockerfile: ./Dockerfile
    env:
      - name: TARGET_IP
        value: "192.168.1.1"
      - name: TARGET_PORT
        value: "80"
      - name: PACKET_SIZE
        value: "200"
      - name: THREADS
        value: "5"
    build:
      command: "pip install -r requirements.txt"
    run:
      command: "chmod +x bgmi"
      command: "python sklate.py"  # Start your script
